UNWIND $rows AS row MERGE (a:Artist {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'HAS_NATIONALITY' MERGE (a)-[r:HAS_NATIONALITY {attribute: row.attribute}]->(n:Nationality {value: row.value}) ON CREATE SET n.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artist {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'HAS_GENDER' MERGE (a)-[r:HAS_GENDER {attribute: row.attribute}]->(g:Gender {value: row.value}) ON CREATE SET g.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artist {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'HAS_BEGIN_DATE' MERGE (a)-[r:HAS_BEGIN_DATE {attribute: row.attribute}]->(bd:BeginDate {value: row.value}) ON CREATE SET bd.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artist {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'HAS_END_DATE' MERGE (a)-[r:HAS_END_DATE {attribute: row.attribute}]->(ed:EndDate {value: row.value}) ON CREATE SET ed.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artist {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'HAS_BIOGRAPHY' MERGE (a)-[r:HAS_BIOGRAPHY {attribute: row.attribute}]->(b:Biography {value: row.value}) ON CREATE SET b.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artist {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'HAS_WIKI_QID' MERGE (a)-[r:HAS_WIKI_QID {attribute: row.attribute}]->(wq:WikiQID {value: row.value}) ON CREATE SET wq.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artist {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'HAS_ULAN' MERGE (a)-[r:HAS_ULAN {attribute: row.attribute}]->(u:ULAN {value: row.value}) ON CREATE SET u.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artwork {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'CREATED_BY_ARTIST' MERGE (a)-[r:CREATED_BY_ARTIST {attribute: row.attribute}]->(ar:Artist {name: row.value}) ON CREATE SET ar.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artwork {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'HAS_DATE' MERGE (a)-[r:HAS_DATE {attribute: row.attribute}]->(d:Date {value: row.value}) ON CREATE SET d.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artwork {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'HAS_MEDIUM' MERGE (a)-[r:HAS_MEDIUM {attribute: row.attribute}]->(m:Medium {value: row.value}) ON CREATE SET m.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artwork {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'HAS_DIMENSIONS' MERGE (a)-[r:HAS_DIMENSIONS {attribute: row.attribute}]->(dim:Dimensions {value: row.value}) ON CREATE SET dim.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artwork {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'HAS_CREDIT_LINE' MERGE (a)-[r:HAS_CREDIT_LINE {attribute: row.attribute}]->(cl:CreditLine {value: row.value}) ON CREATE SET cl.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artwork {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'HAS_ACCESSION_NUMBER' MERGE (a)-[r:HAS_ACCESSION_NUMBER {attribute: row.attribute}]->(an:AccessionNumber {value: row.value}) ON CREATE SET an.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artwork {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'HAS_CLASSIFICATION' MERGE (a)-[r:HAS_CLASSIFICATION {attribute: row.attribute}]->(c:Classification {value: row.value}) ON CREATE SET c.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artwork {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'BELONGS_TO_DEPARTMENT' MERGE (a)-[r:BELONGS_TO_DEPARTMENT {attribute: row.attribute}]->(dep:Department {value: row.value}) ON CREATE SET dep.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artwork {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'HAS_DATE_ACQUIRED' MERGE (a)-[r:HAS_DATE_ACQUIRED {attribute: row.attribute}]->(da:DateAcquired {value: row.value}) ON CREATE SET da.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artwork {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'HAS_CATALOGED_STATUS' MERGE (a)-[r:HAS_CATALOGED_STATUS {attribute: row.attribute}]->(cs:CatalogedStatus {value: row.value}) ON CREATE SET cs.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artwork {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'HAS_OBJECT_ID' MERGE (a)-[r:HAS_OBJECT_ID {attribute: row.attribute}]->(oid:ObjectID {value: row.value}) ON CREATE SET oid.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artwork {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'HAS_URL' MERGE (a)-[r:HAS_URL {attribute: row.attribute}]->(url:URL {value: row.value}) ON CREATE SET url.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artwork {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'HAS_IMAGE_URL' MERGE (a)-[r:HAS_IMAGE_URL {attribute: row.attribute}]->(iurl:ImageURL {value: row.value}) ON CREATE SET iurl.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artwork {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'HAS_ON_VIEW_STATUS' MERGE (a)-[r:HAS_ON_VIEW_STATUS {attribute: row.attribute}]->(ovs:OnViewStatus {value: row.value}) ON CREATE SET ovs.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artwork {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'HAS_CIRCUMFERENCE' MERGE (a)-[r:HAS_CIRCUMFERENCE {attribute: row.attribute}]->(circ:Circumference {value: row.value}) ON CREATE SET circ.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artwork {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'HAS_DEPTH' MERGE (a)-[r:HAS_DEPTH {attribute: row.attribute}]->(dep:Depth {value: row.value}) ON CREATE SET dep.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artwork {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'HAS_DIAMETER' MERGE (a)-[r:HAS_DIAMETER {attribute: row.attribute}]->(dia:Diameter {value: row.value}) ON CREATE SET dia.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artwork {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'HAS_HEIGHT' MERGE (a)-[r:HAS_HEIGHT {attribute: row.attribute}]->(h:Height {value: row.value}) ON CREATE SET h.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artwork {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'HAS_LENGTH' MERGE (a)-[r:HAS_LENGTH {attribute: row.attribute}]->(l:Length {value: row.value}) ON CREATE SET l.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artwork {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'HAS_WEIGHT' MERGE (a)-[r:HAS_WEIGHT {attribute: row.attribute}]->(w:Weight {value: row.value}) ON CREATE SET w.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artwork {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'HAS_WIDTH' MERGE (a)-[r:HAS_WIDTH {attribute: row.attribute}]->(wid:Width {value: row.value}) ON CREATE SET wid.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artwork {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'HAS_SEAT_HEIGHT' MERGE (a)-[r:HAS_SEAT_HEIGHT {attribute: row.attribute}]->(sh:SeatHeight {value: row.value}) ON CREATE SET sh.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (a:Artwork {name: row.name}) ON CREATE SET a.created = timestamp(), a.updated = timestamp() ON MATCH SET a.updated = timestamp() WITH row, a WHERE row.relationship = 'HAS_DURATION' MERGE (a)-[r:HAS_DURATION {attribute: row.attribute}]->(dur:Duration {value: row.value}) ON CREATE SET dur.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()