UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_NATIONALITY' MERGE (artwork)-[r:HAS_NATIONALITY]->(v:Nationality {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_GENDER' MERGE (artwork)-[r:HAS_GENDER]->(v:Gender {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_BEGIN_DATE' MERGE (artwork)-[r:HAS_BEGIN_DATE]->(v:BeginDate {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_END_DATE' MERGE (artwork)-[r:HAS_END_DATE]->(v:EndDate {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_BIOGRAPHY' MERGE (artwork)-[r:HAS_BIOGRAPHY]->(v:Biography {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_WIKI_QID' MERGE (artwork)-[r:HAS_WIKI_QID]->(v:WikiQID {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_ULAN' MERGE (artwork)-[r:HAS_ULAN]->(v:ULAN {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'CREATED_BY_ARTIST' MERGE (artwork)-[r:CREATED_BY_ARTIST]->(v:Artist {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_DATE' MERGE (artwork)-[r:HAS_DATE]->(v:Date {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_MEDIUM' MERGE (artwork)-[r:HAS_MEDIUM]->(v:Medium {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_DIMENSIONS' MERGE (artwork)-[r:HAS_DIMENSIONS]->(v:Dimensions {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_CREDIT_LINE' MERGE (artwork)-[r:HAS_CREDIT_LINE]->(v:CreditLine {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_ACCESSION_NUMBER' MERGE (artwork)-[r:HAS_ACCESSION_NUMBER]->(v:AccessionNumber {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_CLASSIFICATION' MERGE (artwork)-[r:HAS_CLASSIFICATION]->(v:Classification {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'BELONGS_TO_DEPARTMENT' MERGE (artwork)-[r:BELONGS_TO_DEPARTMENT]->(v:Department {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_DATE_ACQUIRED' MERGE (artwork)-[r:HAS_DATE_ACQUIRED]->(v:DateAcquired {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_CATALOGED_STATUS' MERGE (artwork)-[r:HAS_CATALOGED_STATUS]->(v:CatalogedStatus {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_OBJECT_ID' MERGE (artwork)-[r:HAS_OBJECT_ID]->(v:ObjectID {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_URL' MERGE (artwork)-[r:HAS_URL]->(v:URL {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_IMAGE_URL' MERGE (artwork)-[r:HAS_IMAGE_URL]->(v:ImageURL {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_ON_VIEW_STATUS' MERGE (artwork)-[r:HAS_ON_VIEW_STATUS]->(v:OnViewStatus {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_CIRCUMFERENCE' MERGE (artwork)-[r:HAS_CIRCUMFERENCE]->(v:Circumference {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_DEPTH' MERGE (artwork)-[r:HAS_DEPTH]->(v:Depth {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_DIAMETER' MERGE (artwork)-[r:HAS_DIAMETER]->(v:Diameter {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_HEIGHT' MERGE (artwork)-[r:HAS_HEIGHT]->(v:Height {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_LENGTH' MERGE (artwork)-[r:HAS_LENGTH]->(v:Length {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_WEIGHT' MERGE (artwork)-[r:HAS_WEIGHT]->(v:Weight {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_WIDTH' MERGE (artwork)-[r:HAS_WIDTH]->(v:Width {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_SEAT_HEIGHT' MERGE (artwork)-[r:HAS_SEAT_HEIGHT]->(v:SeatHeight {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()

UNWIND $rows AS row MERGE (artwork:ARTWORKMAPPINGS {name: row.name}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_DURATION' MERGE (artwork)-[r:HAS_DURATION]->(v:Duration {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp()