UNWIND $rows AS row MERGE (artist:Artist {name: row.name}) ON CREATE SET artist.created = timestamp(), artist.updated = timestamp() ON MATCH SET artist.updated = timestamp() WITH row, artist WHERE row.relationship = 'HAS_CONSTITUENT_ID' MERGE (artist)-[r:HAS_CONSTITUENT_ID]->(v:ConstituentID {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artist:Artist {name: row.name}) ON CREATE SET artist.created = timestamp(), artist.updated = timestamp() ON MATCH SET artist.updated = timestamp() WITH row, artist WHERE row.relationship = 'HAS_BIO' MERGE (artist)-[r:HAS_BIO]->(v:Bio {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artist:Artist {name: row.name}) ON CREATE SET artist.created = timestamp(), artist.updated = timestamp() ON MATCH SET artist.updated = timestamp() WITH row, artist WHERE row.relationship = 'HAS_NATIONALITY' MERGE (artist)-[r:HAS_NATIONALITY]->(v:Nationality {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artist:Artist {name: row.name}) ON CREATE SET artist.created = timestamp(), artist.updated = timestamp() ON MATCH SET artist.updated = timestamp() WITH row, artist WHERE row.relationship = 'HAS_GENDER' MERGE (artist)-[r:HAS_GENDER]->(v:Gender {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artist:Artist {name: row.name}) ON CREATE SET artist.created = timestamp(), artist.updated = timestamp() ON MATCH SET artist.updated = timestamp() WITH row, artist WHERE row.relationship = 'HAS_BEGIN_DATE' MERGE (artist)-[r:HAS_BEGIN_DATE]->(v:BeginDate {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artist:Artist {name: row.name}) ON CREATE SET artist.created = timestamp(), artist.updated = timestamp() ON MATCH SET artist.updated = timestamp() WITH row, artist WHERE row.relationship = 'HAS_END_DATE' MERGE (artist)-[r:HAS_END_DATE]->(v:EndDate {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artist:Artist {name: row.name}) ON CREATE SET artist.created = timestamp(), artist.updated = timestamp() ON MATCH SET artist.updated = timestamp() WITH row, artist WHERE row.relationship = 'HAS_WIKI_QID' MERGE (artist)-[r:HAS_WIKI_QID]->(v:WikiQID {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artist:Artist {name: row.name}) ON CREATE SET artist.created = timestamp(), artist.updated = timestamp() ON MATCH SET artist.updated = timestamp() WITH row, artist WHERE row.relationship = 'HAS_ULAN' MERGE (artist)-[r:HAS_ULAN]->(v:Ulan {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();
