UNWIND $rows AS row MERGE (artwork:Artwork {objectID: row.objectID}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_ARTIST' MERGE (artwork)-[r:HAS_ARTIST]->(v:Artist {name: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artwork:Artwork {objectID: row.objectID}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_CONSTITUENT_ID' MERGE (artwork)-[r:HAS_CONSTITUENT_ID]->(v:ConstituentID {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artwork:Artwork {objectID: row.objectID}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_ARTIST_BIO' MERGE (artwork)-[r:HAS_ARTIST_BIO]->(v:ArtistBio {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artwork:Artwork {objectID: row.objectID}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_NATIONALITY' MERGE (artwork)-[r:HAS_NATIONALITY]->(v:Nationality {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artwork:Artwork {objectID: row.objectID}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_BEGIN_DATE' MERGE (artwork)-[r:HAS_BEGIN_DATE]->(v:BeginDate {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artwork:Artwork {objectID: row.objectID}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_END_DATE' MERGE (artwork)-[r:HAS_END_DATE]->(v:EndDate {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artwork:Artwork {objectID: row.objectID}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_GENDER' MERGE (artwork)-[r:HAS_GENDER]->(v:Gender {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artwork:Artwork {objectID: row.objectID}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_DATE' MERGE (artwork)-[r:HAS_DATE]->(v:DateVal {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artwork:Artwork {objectID: row.objectID}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_DATE' MERGE (artwork)-[r:HAS_DATE]->(v:DateVal {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artwork:Artwork {objectID: row.objectID}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_DIMENSIONS' MERGE (artwork)-[r:HAS_DIMENSIONS]->(v:Dimensions {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artwork:Artwork {objectID: row.objectID}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_CREDIT_LINE' MERGE (artwork)-[r:HAS_CREDIT_LINE]->(v:CreditLine {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artwork:Artwork {objectID: row.objectID}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_CLASSIFICATION' MERGE (artwork)-[r:HAS_CLASSIFICATION]->(v:Classification {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artwork:Artwork {objectID: row.objectID}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_DATE_ACQUIRED' MERGE (artwork)-[r:HAS_DATE_ACQUIRED]->(v:DateAcquired {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artwork:Artwork {objectID: row.objectID}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_CATALOGED' MERGE (artwork)-[r:HAS_CATALOGED]->(v:Cataloged {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artwork:Artwork {objectID: row.objectID}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_OBJECT_ID' MERGE (artwork)-[r:HAS_OBJECT_ID]->(v:ObjectID {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artwork:Artwork {objectID: row.objectID}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_URL' MERGE (artwork)-[r:HAS_URL]->(v:UrlNode {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artwork:Artwork {objectID: row.objectID}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_URL' MERGE (artwork)-[r:HAS_URL]->(v:UrlNode {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artwork:Artwork {objectID: row.objectID}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_IMAGE_URL' MERGE (artwork)-[r:HAS_IMAGE_URL]->(v:ImageUrl {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artwork:Artwork {objectID: row.objectID}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'IS_ON_VIEW' MERGE (artwork)-[r:IS_ON_VIEW]->(v:OnView {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artwork:Artwork {objectID: row.objectID}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_DEPTH' MERGE (artwork)-[r:HAS_DEPTH]->(v:DepthVal {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artwork:Artwork {objectID: row.objectID}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_DIAMETER' MERGE (artwork)-[r:HAS_DIAMETER]->(v:DiameterVal {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artwork:Artwork {objectID: row.objectID}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_HEIGHT' MERGE (artwork)-[r:HAS_HEIGHT]->(v:HeightVal {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artwork:Artwork {objectID: row.objectID}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_LENGTH' MERGE (artwork)-[r:HAS_LENGTH]->(v:LengthVal {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artwork:Artwork {objectID: row.objectID}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_WEIGHT' MERGE (artwork)-[r:HAS_WEIGHT]->(v:WeightVal {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artwork:Artwork {objectID: row.objectID}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_WIDTH' MERGE (artwork)-[r:HAS_WIDTH]->(v:WidthVal {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artwork:Artwork {objectID: row.objectID}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_SEAT_HEIGHT' MERGE (artwork)-[r:HAS_SEAT_HEIGHT]->(v:SeatHeight {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();

UNWIND $rows AS row MERGE (artwork:Artwork {objectID: row.objectID}) ON CREATE SET artwork.created = timestamp(), artwork.updated = timestamp() ON MATCH SET artwork.updated = timestamp() WITH row, artwork WHERE row.relationship = 'HAS_DURATION' MERGE (artwork)-[r:HAS_DURATION]->(v:DurationVal {value: row.value}) ON CREATE SET v.created = timestamp(), r.updated = timestamp() ON MATCH SET r.updated = timestamp();
